.class public final Lcom/google/android/vending/remoting/protos/VendingProtos;
.super Ljava/lang/Object;
.source "VendingProtos.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/google/android/vending/remoting/protos/VendingProtos$ResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$RequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$AppDataProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$DataMessageProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PendingNotificationsProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PrefetchedBundleProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$SingleResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$SingleRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetAddressSnippetResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetAddressSnippetRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$AddressProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ReconstructDatabaseResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ReconstructDatabaseRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$AssetIdentifierProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$AckNotificationsResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$AckNotificationsRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$CheckForNotificationsResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$CheckForNotificationsRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$InAppPurchaseInformationResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$StatusBarNotificationProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$InAppPurchaseInformationRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$InAppRestoreTransactionsResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$InAppRestoreTransactionsRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$SignedDataProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$SignatureHashProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$BillingEventResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$BillingEventRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$QuerySuggestionResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$QuerySuggestionProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$AppSuggestionProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$QuerySuggestionRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$RestoreApplicationsResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$RestoreApplicationsRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ResponsePropertiesProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$RequestSpecificPropertiesProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$RequestPropertiesProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetCarrierInfoResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetCarrierInfoRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetMarketMetadataResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$BillingParameterProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetMarketMetadataRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$CheckLicenseResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$CheckLicenseRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetCategoriesResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$CategoryProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetCategoriesRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetSubCategoriesResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetSubCategoriesRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetImageResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetImageRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetAssetResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$FileMetadataProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$GetAssetRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PurchaseMetadataResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PurchaseMetadataRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PaypalCountryInfoProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$RemoveAssetRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$RateCommentResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$RateCommentRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$UninstallReasonResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$UninstallReasonRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$RefundResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$RefundRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PaypalMassageAddressResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PaypalMassageAddressRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PaypalPreapprovalCredentialsResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PaypalPreapprovalCredentialsRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PaypalCreateAccountResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PaypalCreateAccountRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PaypalPreapprovalDetailsResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PaypalPreapprovalDetailsRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PaypalPreapprovalResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PaypalPreapprovalRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PurchaseProductResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PurchaseProductRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PurchaseOrderResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PurchaseOrderRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$RiskHeaderInfoProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$InputValidationError;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PurchasePostResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PurchaseCartInfoProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PurchaseResultProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PurchasePostRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$CarrierBillingCredentialsProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PaypalCredentialsProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ExternalPaypalInstrumentProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ExternalCarrierBillingInstrumentProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ExternalCreditCard;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ModifyCommentResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ModifyCommentRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$CommentsResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$CommentsRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$AssetsResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$AssetsRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ExternalCommentProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ExternalAssetProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$DownloadInfoProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ExternalBadgeProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ExternalBadgeImageProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ContentSyncResponseProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$ContentSyncRequestProto;,
        Lcom/google/android/vending/remoting/protos/VendingProtos$PurchaseInfoProto;
    }
.end annotation


# direct methods
.method private constructor <init>()V
    .locals 0

    .prologue
    .line 7
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
