.class public interface abstract Ltwitter4j/Twitter;
.super Ljava/lang/Object;
.source "Twitter.java"

# interfaces
.implements Ljava/io/Serializable;
.implements Ltwitter4j/auth/OAuthSupport;
.implements Ltwitter4j/TwitterBase;
.implements Ltwitter4j/api/SearchMethods;
.implements Ltwitter4j/api/TrendsMethods;
.implements Ltwitter4j/api/TimelineMethods;
.implements Ltwitter4j/api/StatusMethods;
.implements Ltwitter4j/api/UserMethods;
.implements Ltwitter4j/api/ListMethods;
.implements Ltwitter4j/api/ListMembersMethods;
.implements Ltwitter4j/api/ListSubscribersMethods;
.implements Ltwitter4j/api/DirectMessageMethods;
.implements Ltwitter4j/api/FriendshipMethods;
.implements Ltwitter4j/api/FriendsFollowersMethods;
.implements Ltwitter4j/api/AccountMethods;
.implements Ltwitter4j/api/FavoriteMethods;
.implements Ltwitter4j/api/NotificationMethods;
.implements Ltwitter4j/api/BlockMethods;
.implements Ltwitter4j/api/SpamReportingMethods;
.implements Ltwitter4j/api/SavedSearchesMethods;
.implements Ltwitter4j/api/LocalTrendsMethods;
.implements Ltwitter4j/api/GeoMethods;
.implements Ltwitter4j/api/LegalResources;
.implements Ltwitter4j/api/NewTwitterMethods;
.implements Ltwitter4j/api/HelpMethods;
